
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('login_get/', views.login_get),
    path('user_logout/', views.user_logout),
    path('login_post/', views.login_post),
    path('admin_home/', views.admin_home),
    path('admin_complaints/', views.admin_complaints),
    path('admin_addcoordinator/', views.admin_addcoordinator),
    path('admin_add_cord_post/', views.admin_add_cord_post),
    path('admin_viewcoordinators/', views.admin_viewcoordinators),
    path('admin_editcoordinator/<id>', views.admin_editcoordinator),
    path('admin_edit_cord_post/', views.admin_edit_cord_post),
    path('admin_del_coordinator/<id>', views.admin_del_coordinator),
    path('admin_Event/', views.admin_Event),
    path('admin_feedback/', views.admin_feedback),
    path('admin_reply/<id>', views.admin_reply),
    path('admin_reply_post/', views.admin_reply_post),
    path('admin_user/', views.admin_user),
    path('coordinator_home/', views.coordinator_home),
    path('coordinator_viewevent/', views.coordinator_viewevent),
    path('cordinator_addevent/', views.cordinator_addevent),
    path('cordinator_addevent_post/', views.cordinator_addevent_post),
    path('coordinator_sendreply/', views.coordinator_sendreply),
    path('coordinator_verifyevent/', views.coordinator_verifyevent),
    path('coord_reject_event/<id>', views.coord_reject_event),
    path('coord_accept_event/<id>', views.coord_accept_event),
    path('coordinator_viewcomplaints/', views.coordinator_viewcomplaints),
    path('coordinator_viewfeedback/', views.coordinator_viewfeedback),
    path('cordinator_editevent/<id>', views.cordinator_editevent),
    path('cordinator_editevent_post/', views.cordinator_editevent_post),
    path('cordinator_del_event/<id>', views.cordinator_del_event),

    #################flutter####################
    path('gemini_chat/', views.gemini_chat),
    path('viewprofile/', views.viewprofile),
    path('updateprofile/', views.updateprofile),
    path('loginpost/', views.loginpost),
    path('user_register/', views.user_register),
    path('send_complaint_user/', views.send_complaint_user),
    path('complaintViewflutter/', views.complaintViewflutter),
    path('sendfeedback_post/', views.sendfeedback_post),
    path('view_events/', views.view_events),
    path('Add_event/', views.Add_event),
    path('view_followlist/', views.view_followlist),
    path('User_sendchat/', views.User_sendchat),
    path('User_viewchat/', views.User_viewchat),
    path('delete_event/', views.delete_event),
    # path('NLP_search_event_recommendation/', views.NLP_search_event_recommendation),
    path('view_user/', views.view_user),
    path('follow_user/', views.follow_user),
    path('unfollow_user/', views.unfollow_user),
    path('change_passwordpost_user/', views.change_passwordpost_user),
    path('AspectBasedEventRecommendation/', views.AspectBasedEventRecommendation),
    path('calculate_distance/', views.calculate_distance),
    path('NearbyEventRecommendation/', views.NearbyEventRecommendation),
    path('get_new_events/', views.get_new_events),
    path('view_eventsaccepted/', views.view_eventsaccepted),
    # path('chatfromusettouser/', views.chatfromusettouser),

]
