# Generated by Django 5.2.6 on 2025-12-04 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phoneno', models.BigIntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Photo', models.FileField(upload_to='')),
                ('Gender', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Details', models.CharField(max_length=300)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Link', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phoneno', models.BigIntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Image', models.FileField(upload_to='')),
                ('Gender', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='myapp.userstable')),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tid', to='myapp.userstable')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.CharField(max_length=50)),
                ('Rating', models.FloatField()),
                ('Aspect', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eventtable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userstable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=100)),
                ('Reply', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userstable')),
            ],
        ),
        migrations.CreateModel(
            name='ChatTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfid', to='myapp.userstable')),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctid', to='myapp.userstable')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userstable')),
            ],
        ),
    ]
